/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package act3;

import javax.swing.JOptionPane;

/**
 *
 * @author madro
 */
public class NewJFrame extends javax.swing.JFrame {

    static float total;
    static float paytotal;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Label1 = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        Costnumlabel = new javax.swing.JLabel();
        Ordermode = new javax.swing.JLabel();
        DineinRbutton = new javax.swing.JRadioButton();
        TakeoutRbutton = new javax.swing.JRadioButton();
        Product = new javax.swing.JLabel();
        Cbox1 = new javax.swing.JCheckBox();
        Cbox2 = new javax.swing.JCheckBox();
        Cbox3 = new javax.swing.JCheckBox();
        Cbox4 = new javax.swing.JCheckBox();
        CBox5 = new javax.swing.JCheckBox();
        CBox6 = new javax.swing.JCheckBox();
        CORDButton1 = new javax.swing.JButton();
        CORDButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Label1.setText("COSTUMER INFORMATION");

        NameLabel.setText("NAME");

        Costnumlabel.setText("CONTACT NUMBER");

        Ordermode.setText("ORDER MODE");

        buttonGroup1.add(DineinRbutton);
        DineinRbutton.setText("DINE IN");

        buttonGroup1.add(TakeoutRbutton);
        TakeoutRbutton.setText("TAKE OUT");
        TakeoutRbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeoutRbuttonActionPerformed(evt);
            }
        });

        Product.setText("PRODUCTS");

        Cbox1.setText("PLAIN BURGER (P 25.00)");

        Cbox2.setText("CHEESE BURGER (P 30.00)");

        Cbox3.setText("CHEESE BURGER WITH EGG (P 35.00)");

        Cbox4.setText("HOTDOG (P 10.00)");

        CBox5.setText("HOTDOG WITH BUN (P 15.00)");

        CBox6.setText("HOTDOG WITH CHEESE ON BUN (P 35,00)");

        CORDButton1.setBackground(new java.awt.Color(102, 255, 102));
        CORDButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CORDButton1.setText("CHECK ORDER");
        CORDButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORDButton1ActionPerformed(evt);
            }
        });

        CORDButton2.setBackground(new java.awt.Color(102, 255, 102));
        CORDButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CORDButton2.setText("PROCEED PAYMENT");
        CORDButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CORDButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Product, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbox3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(Cbox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cbox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(CORDButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBox6)
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addComponent(CBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cbox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(CORDButton2)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ordermode, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DineinRbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(TakeoutRbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Costnumlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(Costnumlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(Ordermode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DineinRbutton)
                    .addComponent(TakeoutRbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Product)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbox1)
                    .addComponent(Cbox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBox5)
                    .addComponent(Cbox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbox3)
                    .addComponent(CBox6))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CORDButton1)
                    .addComponent(CORDButton2))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TakeoutRbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeoutRbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TakeoutRbuttonActionPerformed

    private void CORDButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORDButton1ActionPerformed
        // Check Order Option
        String OMode = "";
        String Product = "";
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Name is empty!", null, HEIGHT);
            return;
        }
        if(!jTextField1.getText().matches("[ a-zA-Z]+"))
        {
            JOptionPane.showMessageDialog(rootPane, "Invalid Input in Name! ", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(contact.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Contact is empty!", null, HEIGHT);
            return;
        }
        if(!contact.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(rootPane, "Invalid input in contacts", null, HEIGHT);
            return;
        }
        if(DineinRbutton.isSelected()){
            OMode += "Dine In ";
        }
        if(TakeoutRbutton.isSelected()){
            OMode += "Take Out ";
        }
        if(Cbox1.isSelected()){
            Product += "\nPLAIN BURGER (P 25.00) ";
            total += 25;
        }
        if(Cbox2.isSelected()){
            Product += "\nCHEESE BURGER (P 30.00)";
            total += 30;
        }
        if(Cbox3.isSelected()){
            Product += "\nCHEESE BURGER WITH EGG (P 35.00)";
            total += 35;
        }
        if(Cbox4.isSelected()){
            Product += "\nHOTDOG (P 10.00)";
            total += 10;
        }
        if(CBox5.isSelected()){
            Product += "\nHOTDOG WITH BUN (P 15.00)";
            total += 15;
        }
         if(CBox6.isSelected()){
            Product += "\nHOTDOG WITH CHEESE ON BUN (P 35,00)";
            total += 35;
        }
         if(DineinRbutton.isSelected()){
            total += (total*10/100);
            
        }
         if(TakeoutRbutton.isSelected()){
            total -= (total*5/100);
            
        }JOptionPane.showMessageDialog(rootPane, "Name: "+jTextField1.getText()+"\nContact No. "+contact.getText()+"\n\nOrder Mode: "+OMode+"\nProducts:"+Product, null, JOptionPane.INFORMATION_MESSAGE);
         total = 0;
         
    }//GEN-LAST:event_CORDButton1ActionPerformed

    private void CORDButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CORDButton2ActionPerformed
        // TODO add your handling code here:
        paymentform pay = new paymentform();
        pay.setVisible(true);
        
        String orderm = "";
        String AddInfo = "";
        String ProdInfo = "";
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Name is Empty", null, JOptionPane.OK_OPTION);
            return;
        }
        if(contact.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Contact is Empty", null, JOptionPane.OK_OPTION);
            return;
        }
        if(!contact.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(rootPane, "Invalid Input in Contact\nUse Numbers Only", null, JOptionPane.OK_OPTION);
            return;
        }
        if(!DineinRbutton.isSelected() && !TakeoutRbutton.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "No Order Mode\nPlease Select Order Mode", null, JOptionPane.OK_OPTION);
            return;
        }
        if(DineinRbutton.isSelected()){
            orderm += "Dine In ";
            AddInfo += "Dine In orders is charged by 10%.";
        }
        if(TakeoutRbutton.isSelected()){
            orderm += "Take Out ";
            AddInfo += "Take Out orders is discounted by 5%.";
        }
        if(!Cbox1.isSelected() && !Cbox2.isSelected() && !Cbox3.isSelected() && !Cbox4.isSelected() && !CBox5.isSelected() && !CBox6.isSelected()){
            JOptionPane.showMessageDialog(rootPane, "No Product's Selected!!!", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(Cbox1.isSelected()){
            ProdInfo += "\nPLAIN BURGER (P 25.00)\n";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 25;
        }if(Cbox2.isSelected()){
            ProdInfo += "\nCHEESE BURGER (P 30.00)\n";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 30;
        }
        if(Cbox3.isSelected()){
            ProdInfo += "\nCHEESE BURGER WITH EGG (P 35.00) ";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 35;
        }
        if(Cbox4.isSelected()){
            ProdInfo += "\nHOTDOG (P 10.00) ";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 10;
        }
        if(CBox5.isSelected()){
            ProdInfo += "\nHOTDOG WITH BUN (P 15.00) ";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 15;
        }
        if(CBox6.isSelected()){
            ProdInfo += "\nHOTDOG WITH CHEESE ON BUN (P 35.00) ";
            paymentform.model.addElement(ProdInfo);
            paymentform.jList1.setModel(paymentform.model);
            ProdInfo = "";
            paytotal += 35;
        }
        if(DineinRbutton.isSelected()){
            
            paytotal += (paytotal * 10/100);
        }
        if(TakeoutRbutton.isSelected()){
            
            paytotal -= (paytotal * 5/100);
        }
       String ctotal = Float.toString(paytotal);
        
        paymentform.name.setText(jTextField1.getText());
        paymentform.contact.setText(contact.getText());
        paymentform.orderm.setText(orderm);
        paymentform.totalp.setText(ctotal);
        paymentform.orderm.setText(AddInfo);
       
      
    }//GEN-LAST:event_CORDButton2ActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CBox5;
    private javax.swing.JCheckBox CBox6;
    private javax.swing.JButton CORDButton1;
    private javax.swing.JButton CORDButton2;
    private javax.swing.JCheckBox Cbox1;
    private javax.swing.JCheckBox Cbox2;
    private javax.swing.JCheckBox Cbox3;
    private javax.swing.JCheckBox Cbox4;
    private javax.swing.JLabel Costnumlabel;
    private javax.swing.JRadioButton DineinRbutton;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel Ordermode;
    private javax.swing.JLabel Product;
    private javax.swing.JRadioButton TakeoutRbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contact;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
